name: Trigger auto deployment for c3-ui-v2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/c3-ui-v2-AutoDeployTrigger-a89f38d2-f6e2-4b39-82b0-263aa127afbf.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.C3UIV2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.C3UIV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.C3UIV2_REGISTRY_PASSWORD }}
          containerAppName: c3-ui-v2
          resourceGroup: c3-containerapps
          imageToBuild: luting47/c3-ui-v2:${{ github.sha }}
          dockerfilePath: Dockerfile

     

