name: Trigger auto deployment for c3-ui-v2

# When this action will be executed
on:
  # Automatically trigger it when CI tests pass
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.C3UIV2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.C3UIV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.C3UIV2_REGISTRY_PASSWORD }}
          containerAppName: c3-ui-v2
          resourceGroup: c3-containerapps
          imageToBuild: luting47/c3-ui:${{ github.sha }}
          dockerfilePath: Dockerfile

     

